
root: /kab

menu:
  Home: /kab
  Tags: /kab/tags

language: ja

author:
description:

github:
email:

favicon: /favicon.ico


# stylesheets loaded in the <head>
stylesheets:
- /kab/css/hexo-theme-adoubi.css
