
root: /web

Home: /web
Archives: /archives
About: /about

language: ja

author:
description:

github:
email:

favicon: /favicon.ico


# stylesheets loaded in the <head>
stylesheets:
- /web/css/hexo-theme-adoubi.css
