
root: /web

menu:
  Home: /web
  Tags: /web/tags

language: ja

author:
description:

github:
email:

favicon: /favicon.ico


# stylesheets loaded in the <head>
stylesheets:
- /web/css/hexo-theme-adoubi.css
